apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic-service.fullname" . }}
  labels: {{ include "generic-service.default-labels" . | nindent 4 }}

data:
  data.yaml: {{ .Values.config | toYaml | quote }}
